doc: Added documentation for AD719X project
analogdevicesinc/precision-converters-firmware pull request #45
Opened 2024-02-07 09:11 UTC by D-Disha

Added sphinx documentation.

2024-02-07 09:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/analogdevicesinc/precision-converters-firmware?pullRequest=45) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/analogdevicesinc/precision-converters-firmware?pullRequest=45) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/analogdevicesinc/precision-converters-firmware?pullRequest=45) it.</sub>

2024-02-13 06:57 UTC, SaikiranGudla commented
Looks good to me.
Suggest to squash commits by not adding extra commits for review changes. 
A changelog in the PR discussion thread similar to no-os would be better.

2024-02-13 08:43 UTC, D-Disha commented
Added documentation support for ad7124 console application. 
The wiki link for ad7124 console : https://wiki.analog.com/resources/tools-software/product-support-software/ad7124_mbed_support

2024-02-13 09:40 UTC, SaikiranGudla requested changes

2024-02-13 09:40 UTC, SaikiranGudla commented on doc/sphinx/source/projects/ad7124_console/ad7124_console.rst
> +   .. image:: /source/projects/ad7124_console/ad7124_software_sequence.jpg
Shall the image be attached after the line 118 following the description written which says "AD7124 Firmware Example is **shown below**" (line114) ?

2024-02-13 09:40 UTC, SaikiranGudla commented on doc/sphinx/source/projects/ad7124_console/ad7124_console.rst
> +If you have some familiarity with the Mbed platform, the following is a basic list of steps required to start running the code,
I think Quick Start needs to be modified a bit as building and flashing the binary is already covered in the Build section.
Lines 128 to 137 are redundant and there isn't a Downloads section as mentioned in line 133.

2024-02-15 07:12 UTC, D-Disha commented
Changelog: Updated Quick start and moved the software layers image

2024-02-15 08:45 UTC, SaikiranGudla approved these changes

2024-02-15 09:57 UTC, D-Disha commented
Hi @CMinajigi @ribdp, are there any more comments or does this PR look good for merge?

2024-02-15 10:35 UTC, ribdp commented on doc/sphinx/source/projects/ad7124_console/ad7124_console.rst
> +The AD7124-EVAL board is connected to SDP-K1 through default 120-pin SDP Connector. The AD7124-EVAL board has external connector to connect
Should we leave out 'default' here?

2024-02-27 11:48 UTC, SaikiranGudla commented on doc/sphinx/source/projects/ad717x_console/ad717x_console.rst
> +The AD717x/ AD411x family offer a complete integrated Sigma-Delta ADC solution which can be used in high precision, low noise single channel applications (Life Science measurements) or higher speed m
nit: remove extra space after "/"

2024-02-27 11:49 UTC, SaikiranGudla commented on doc/sphinx/source/projects/ad717x_console/ad717x_console.rst
> +The EVAL-AD411x/ EVAL-AD717x board is connected to SDP-K1 through on-board default 120-pin SDP Connector. The AD717x/AD411x EVAL boards can be powered-up through a SDP-K1 USB supply or from external
nit: remove extra space after "/"

2024-02-27 13:52 UTC, merged