Use Doctools
analogdevicesinc/precision-converters-firmware pull request #54
Opened 2024-03-25 16:22 UTC by gastmaier

2024-03-25 16:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/analogdevicesinc/precision-converters-firmware?pullRequest=54) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/analogdevicesinc/precision-converters-firmware?pullRequest=54) before we can accept your contribution.<br/>**6** out of **7** committers have signed the CLA.<br/><br/>:white_check_mark: D-Disha<br/>:white_check_mark: mphalke<br/>:white_check_mark: SaikiranGudla<br/>:white_check_mark: ribdp<br/>:white_check_mark: jansunil<br/>:white_check_mark: CMinajigi<br/>:x: gastmaier<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/analogdevicesinc/precision-converters-firmware?pullRequest=54) it.</sub>

2024-03-25 16:38 UTC, gastmaier commented
Also note that the `Documentation/Update gh pages` CI is running for PRs,
I recommend removing [on: pull_request](https://github.com/analogdevicesinc/precision-converters-firmware/actions/runs/8423437925/workflow?pr=54#L3) from the ci file.
Or having different targets (e.g, on pull_request build the doc but do not push to gh_pages branch)

2024-03-29 07:02 UTC, SaikiranGudla requested changes
@gastmaier, the overall structure looks good, but I noticed a few issues on the github pages live preview from your forked repo.

1. The image "identifying_virtual_serial_port.png" part of the comm_interface.rst doesn't seem to show up as an image on the page. Here: https://gastmaier.github.io/adi-precision-converters-firmware/source/projects/ad579x_iio/ad579x_iio.html#communication-interface
2. Similar issue was observed over here as well, https://gastmaier.github.io/adi-precision-converters-firmware/source/projects/ad4696_iio/ad4696_iio.html#hardware-connections
3. It's good that you have done the necessary changes in the project_build.rst but this section is also being used in all the project specific rst files and I see that the project specific contents are a bit unaligned. I think the "Build Prerequisites", "Building a Project", etc. should be under the Build Guide section but not the main sections themselves.
![image](https://github.com/analogdevicesinc/precision-converters-firmware/assets/118167755/95cdfe0f-fe41-4824-bec9-3a9571ec4e0b)
This shall also fix the table of contents as shown here, 
![image](https://github.com/analogdevicesinc/precision-converters-firmware/assets/118167755/47bd12e3-07cd-451d-8138-3e91fb2fa8c6)

2024-04-01 13:01 UTC, gastmaier commented
1. `identifying_virtual_serial_port.png` doesn't exist in the repo and the problem existed before this commit;
at d10867e7ab1da2fc8eca00689aeeda90caf867ba `doc:Adding doc for ad777x_iio and nanodac_console`:
```
/mnt/wsl/data/repos/precision-converters-firmware/doc/sphinx/source/hardware/comm_interface.rst:: WARNING: image file not readable: source/hardware/identifying_virtual_serial_port.png
```

2. Same as above

3. There is an issue with the nesting/includes across the doc:
The part pages start with:
```
ADXXXX IIO Application
------------------------
```
Then the sections header are:
```
==========
Placeholder Text
==========
```
And finally the included page starts with
```
=======
Build Guide
=======

Build Prerequisites
--------------------
```
That means, `ADXXXX IIO Application` and `Build Prerequisites` are in the same header level ([H1](https://www.w3schools.com/tags/tag_hn.asp)), causing the odd behavior. 

Sphinx sets the header level by first appearance, for example, if `~~~~~~~` appears first, it takes the H1 position.

A quick fix is to change the *_iio.rst header to:
```
ADXXXX IIO Application
===============
```
Setting `==` as the H1 level, still not perfect, since the other sections should be `---` instead of `===` to take the H2 level.
Other solution is to change to:
```
ADXXXX IIO Application
""""""""""""""""""""""""""""""
```
Now, the `"""` takes H1 position, `===` H2, `---` H3, and so on, and searching recursively, `"""` is never used in this doc.
```
doc/sphinx$ grep -rn '"""' .
````

2024-04-05 15:22 UTC, SaikiranGudla approved these changes

2024-04-07 06:31 UTC, merged